name: CD
on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.json'
jobs:
  update:
    if: github.repository_owner == 'PreMiD'
    name: Update Presences
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        run: HUSKY=0 npm ci
      - name: Update Presences
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: npm run presenceUpdater push
