name: pmd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pmd:
    name: Run compile, and metadata check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm

      - name: Install PMD
        run: HUSKY=0 npm ci

      - name: Run PMD
        run: npx pmd build --changed --no-kill --check-metadata --sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-results.sarif
          wait-for-processing: true
